# This workflow will build a Swift project

name: Local

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: SwiftyLab/setup-swift@latest
    - name: Get swift version
      run: swift --version
    - name: Get swift version in macOS
      if: runner.os == 'macOS'
      run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Build
      run: sh build.sh
    - name: Run tests
      run: swift test
